controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    quadruped_controller:
      type: joint_trajectory_controller/JointTrajectoryController

quadruped_controller:
  ros__parameters:
    joints:
      - leg1_a
      - leg1_b
      - leg1_c
      - leg2_a
      - leg2_b
      - leg2_c
      - leg3_a
      - leg3_b
      - leg3_c
      - leg4_a
      - leg4_b
      - leg4_c

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      
      leg1_a:
        trajectory: 0.05
        goal: 0.03